name: Java CI with Docker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Test with Maven
      run: mvn test
    
    # Log into Docker Hub
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    # Build the Docker image
    - name: Build Docker image
      run: docker build -t your-dockerhub-username/your-repo-name:your-tag .

    # Push the Docker image to Docker Hub
    - name: Push Docker image to DockerHub
      run: docker push your-dockerhub-username/your-repo-name:your-tag
